server:
  port: 9080
  context-path: /

spring:
  datasource:
    url: jdbc:mysql://172.17.21.59:3306/eaccount?allowMultiQueries=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  redis:
    host: 172.17.21.59
    password: 123456
    port: 7000
  session:
    store-type: none

mybatis:
  mapper-locations: classpath:sql/mapper/*.xml

logging:
  level:
    root: INFO
    com.ucsmy.eaccount.pay: DEBUG

# serialNumber配置示例
# 提供serialNumber生成策略：1.redis自增(redisIncrement)；
# 序列号生成器配置，格式：4位前缀 + 8位日期 + 6位流水号，限制长度必须为18位，目前长度不支持配置
ucsmy.serialNumber:
  # 生成模式，见GeneratorMode
  mode: redis
  # redis模式下的key命名空间
  namespace: eaccount:pay
  # 默认前缀
  prefix: 1000
  # 备用前缀
  backupPrefix: 9999
  # 序列部分起始基数
  startNum: 1
  # 序列号日期格式
  datePattern: yyMMddHH